apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "mariadb.name" . }}"
data:
    mariadb-user: {{ .Values.database.mariabdbuser | quote }}
    mariadb-database: {{ .Values.database.mariadbdatabase | quote }}
    allowemptypassword: {{ .Values.database.allowemptypassword | quote }}