apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mariadb.fullname" . }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
