apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: "{{ index .Values.database.mariadbrootpassword | b64enc }}"
  mariadb-password: "{{ index .Values.database.mariadbpassword | b64enc }}"